CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE workspaces (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE users (id uuid PRIMARY KEY, workspace_id uuid NOT NULL REFERENCES workspaces(id), email text NOT NULL, name text NOT NULL, role text NOT NULL CHECK (role IN ('requester','agent','administrator')), UNIQUE (workspace_id, email));
CREATE TABLE ticket_categories (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid NOT NULL REFERENCES workspaces(id), name text NOT NULL, UNIQUE (workspace_id, name));
CREATE TABLE tickets (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid NOT NULL REFERENCES workspaces(id), number bigint GENERATED ALWAYS AS IDENTITY, requester_id uuid NOT NULL REFERENCES users(id), assignee_id uuid REFERENCES users(id), category_id uuid REFERENCES ticket_categories(id), title text NOT NULL, description text NOT NULL, status text NOT NULL DEFAULT 'open' CHECK (status IN ('open','in_progress','waiting','resolved','closed')), priority text NOT NULL DEFAULT 'normal' CHECK (priority IN ('low','normal','high','urgent')), resolved_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE (workspace_id, number));
CREATE TABLE ticket_comments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), ticket_id uuid NOT NULL REFERENCES tickets(id) ON DELETE CASCADE, author_id uuid NOT NULL REFERENCES users(id), body text NOT NULL, is_internal boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE ticket_attachments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), ticket_id uuid NOT NULL REFERENCES tickets(id) ON DELETE CASCADE, comment_id uuid REFERENCES ticket_comments(id) ON DELETE CASCADE, object_key text NOT NULL UNIQUE, filename text NOT NULL, content_type text NOT NULL, size_bytes bigint NOT NULL, uploaded_by uuid NOT NULL REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE ticket_activities (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), ticket_id uuid NOT NULL REFERENCES tickets(id) ON DELETE CASCADE, actor_id uuid REFERENCES users(id), action text NOT NULL, metadata jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX ticket_queue_idx ON tickets (workspace_id, status, priority, updated_at DESC);
